using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace COMP1551_SeaAnimal_Game
{
    class User : ParentUserAndPGSS, IUser
    {
        public User(): this("Unknown")
        {
        }

        public User(string username)
        {
            Username = username;
        }

        public override string ToString()
        {
            return String.Format(assign + "{0}", Username);
        }

        public void interfacesMessage()
        {
            Console.WriteLine("This message was generated by using interfaces (IUser).");
        }

        public void errorCheck()
        {
            Console.WriteLine("If you are able to view this notification, there is no error with the start page.");
        }

        public void greetingToUser()
        {
            Console.WriteLine("Welcome to Sea Animal Game, players.");
        }

        public void meaningOfGame()
        {
            Console.WriteLine("Playing this game will teach you about ocean life. ");
            Console.WriteLine("For those who want to learn more about the ocean, this game is educational.");
        }

        public void exitLine()
        {
            Console.WriteLine("I hope you enjoy the game and have a fantastic day.");
        }
    }
}
